import type {Metadata, Viewport} from "next";
import {UserProvider} from "@auth0/nextjs-auth0/client";

export const metadata: Metadata = {
    title: "Create Next App", description: "Generated by create next app",
};

export const viewport: Viewport = {
    initialScale: 1, maximumScale: 1, width: 'device-width', userScalable: false,
}


export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (<html lang="en">
        <body
            className="h-dvh bg-secondary"
        >
        <UserProvider>
            {children}
        </UserProvider>
        </body>
        </html>);
}
